dataset_params:
  im_path: '/ssd_scratch/abhishek/alot_png4/png4'

diffusion_params:
  num_timesteps : 1000
  beta_start : 0.0001
  beta_end : 0.02

model_params:
  im_channels : 3
  im_size : 28
  down_channels : [32, 64, 128, 256]
  mid_channels : [256, 256, 128]
  down_sample : [True, True, False]
  time_emb_dim : 128
  num_down_layers : 2
  num_mid_layers : 2
  num_up_layers : 2
  num_heads : 4

train_params:
  task_name: 'default'
  batch_size: 64
  num_epochs: 80
  num_samples : 1
  num_grid_rows : 1
  lr: 0.0001
  ckpt_name: 'textures_ddpm_ckpt.pth'
